[package]
name = "hmc"
description = "HiveMe CLI: send a message to the MQTT broker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "hmc"
path = "src/main.rs"

[dependencies]
hiveme-core = { workspace = true }
